# Generated by Django 4.1.5 on 2023-05-28 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_alter_espacio_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='Sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.facultad'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.sede'),
        ),
    ]
