# Generated by Django 4.1.5 on 2023-05-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_alter_departamento_sede_alter_facultad_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='Sede',
            new_name='Facultad',
        ),
        migrations.RenameField(
            model_name='facultad',
            old_name='Departamento',
            new_name='Sede',
        ),
    ]
