# Generated by Django 4.1.5 on 2023-05-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_rename_sede_departamento_facultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='Nombre',
            field=models.CharField(max_length=120),
        ),
    ]
