# Generated by Django 4.1.5 on 2023-06-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_prerequisito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prerequisito',
        ),
    ]
