# Generated by Django 4.1.5 on 2023-06-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_delete_prerequisito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisito',
            fields=[
                ('Id_Prerequisito', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('Prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prerequisito', to='academico.asignatura')),
            ],
            options={
                'verbose_name': 'Prerequisito',
                'verbose_name_plural': 'Prerequisitos',
                'db_table': 'Prerequisito',
            },
        ),
    ]
